# Generated by Django 5.1.7 on 2025-04-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
